import{a as p,S as b,i as q}from"./assets/vendor-c493984e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&u(l)}).observe(document,{childList:!0,subtree:!0});function d(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function u(t){if(t.ep)return;t.ep=!0;const a=d(t);fetch(t.href,a)}})();p.defaults.baseURL="https://pixabay.com/api/";const o={query:"",page:1,perPage:15,maxPAge:""};function m(){const e={params:{key:"43998127-099fd85a2e7628fabdc2ccde0",image_type:"photo",orientation:"horizontal",safesearch:!0,q:o.query,page:o.page,per_page:o.perPage}};return p.get("",e)}function y(e){return e.map(v).join("")}function v(e){return`<li class="gallery-item">
<div class='gallery'>
  <a class="img-link" href="${e.largeImageURL}">
    <img class="img-item" src="${e.webformatURL}" alt="${e.tags}" />
  </a>
</div>
<div class='text-box'>
        <p class="text">Likes ${e.likes}</p>
        <p class="text">Views ${e.views}</p>
        <p class="text">Comments ${e.comments}</p>
        <p class="text">Downloads ${e.downloads}</p>
  </div>
</li>`}let h=new b(".js-gallery a",{captionsData:"alt",captionDelay:250});const s={formEl:document.querySelector(".js-form"),inputEl:document.querySelector(".js-input"),galleryEl:document.querySelector(".js-gallery"),loader:document.querySelector(".loader"),btnLoad:document.querySelector(".js-btn-load")};s.formEl.addEventListener("submit",P);s.btnLoad.addEventListener("click",E);function P(e){if(e.preventDefault(),s.galleryEl.innerHTML="",n(),o.query=e.target.elements.query.value.trim(),o.page=1,L(),o.query===""){i("Please enter a search query","tomato"),c();return}w(),e.target.reset()}async function w(){try{const{data:{hits:e,totalHits:r}}=await m(o.query);if(f(),e.length===0){n(),i("Sorry, there are no images matching your search query. Please try again!","red");return}s.galleryEl.innerHTML=y(e),h.refresh(),r<o.perPage?n():f()}catch(e){console.log(e)}finally{c()}}async function E(){L(),o.page+=1;try{const{data:{hits:e,totalHits:r}}=await m();if(e.length===0){i("We are sorry, but you`ve reached the end of search results","DeepSkyBlue"),n();return}Math.ceil(r/o.perPage)===o.page&&n(),s.galleryEl.insertAdjacentHTML("beforeend",y(e)),g(),h.refresh()}catch{i("Error","red")}finally{c(),g()}}function i(e,r){q.error({title:"",message:e,position:"topRight",backgroundColor:r,messageColor:"white"})}function L(){s.loader.classList.remove("is-hidden")}function c(){s.loader.classList.add("is-hidden")}function f(){s.btnLoad.classList.remove("is-hidden")}function n(){s.btnLoad.classList.add("is-hidden")}function g(){const r=s.galleryEl.firstChild.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
