import{a as u,S as L,i as b}from"./assets/vendor-c493984e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function h(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=h(t);fetch(t.href,r)}})();u.defaults.baseURL="https://pixabay.com/api/";const s={query:"",page:1,perPage:15,maxPAge:""};function f(){const e={params:{key:"43998127-099fd85a2e7628fabdc2ccde0",image_type:"photo",orientation:"horizontal",safesearch:!0,q:s.query,page:s.page,per_page:s.perPage}};return u.get("",e)}function p(e){return e.map(E).join("")}function E(e){return`<li class="gallery-item">
<div class='gallery'>
  <a class="img-link" href="${e.largeImageURL}">
    <img class="img-item" src="${e.webformatURL}" alt="${e.tags}" />
  </a>
</div>
<div class='text-box'>
        <p class="text">Likes ${e.likes}</p>
        <p class="text">Views ${e.views}</p>
        <p class="text">Comments ${e.comments}</p>
        <p class="text">Downloads ${e.downloads}</p>
  </div>
</li>`}let m=new L(".js-gallery a",{captionsData:"alt",captionDelay:250});const a={formEl:document.querySelector(".js-form"),inputEl:document.querySelector(".js-input"),galleryEl:document.querySelector(".js-gallery"),loader:document.querySelector(".loader"),btnLoad:document.querySelector(".js-btn-load")};a.formEl.addEventListener("submit",q);a.btnLoad.addEventListener("click",w);async function q(e){if(e.preventDefault(),a.galleryEl.innerHTML="",s.query=e.target.elements.query.value.trim(),s.page=1,g(),s.query===""){n("Please enter a search query","tomato"),l();return}await v(),e.target.reset()}async function v(){try{const{data:{hits:e}}=await f(s.query);if(x(),e.length===0){y(),n("Sorry, there are no images matching your search query. Please try again!","red");return}a.galleryEl.innerHTML=p(e);const o=a.inputEl.firstChild;m.refresh()}catch(e){console.log(e)}finally{l()}}async function w(){g(),s.page+=1;try{const{data:{hits:e}}=await f();if(e.length===0){n("We are sorry, but you`ve reached the end of search results","DeepSkyBlue"),y();return}a.galleryEl.insertAdjacentHTML("beforeend",p(e)),d(),m.refresh()}catch{n("Error","red")}finally{l(),d()}}function n(e,o){b.error({title:"",message:e,position:"topRight",backgroundColor:o,messageColor:"white"})}function g(){a.loader.classList.remove("is-hidden")}function l(){a.loader.classList.add("is-hidden")}function x(){a.btnLoad.classList.remove("is-hidden")}function y(){a.btnLoad.classList.add("is-hidden")}function d(){const o=a.galleryEl.firstChild.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
